name: Update BPMN Visualization version
on:
  repository_dispatch:
    types: [ update_bpmn_visualization_version ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  updateVersion:
    runs-on: ubuntu-22.04
    env:
      VERSION: ${{ github.event.client_payload.version || github.event.inputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Get old bpmn-visualization version
        id: lookupOldBPMNVisuVersion
        uses: mikefarah/yq@v4.30.5
        with:
          cmd: yq '.dependencies[] | select(.name == "bpmn-visualization") | .version' inst/htmlwidgets/bpmnVisualization.yaml
      - run: echo "OLD_VERSION=${{ steps.lookupOldBPMNVisuVersion.outputs.result }}" >> $GITHUB_ENV
      - name: Delete old bpmn-visualization js lib file
        run: rm inst/htmlwidgets/lib/bpmn-visualization/bpmn-visualization.min.js
      - name: Download bpmn-visualization ${{ env.VERSION }}
        uses: carlosperate/download-file-action@v2
        with:
          file-url: 'https://cdn.jsdelivr.net/npm/bpmn-visualization@${{ env.VERSION }}/dist/bpmn-visualization.min.js'
          location: 'inst/htmlwidgets/lib/bpmn-visualization'
      - name: Update bpmn-visualization version in YAML file
        run: |
          sed -i -E 's/version: ".*"/version: "${{ env.VERSION }}"/' inst/htmlwidgets/bpmnVisualization.yaml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.3
        with:
          token: ${{ secrets.GH_RELEASE_TOKEN }}
          commit-message: "[INFRA] Bump bpmn-visualization JS lib from ${{ env.OLD_VERSION }} to ${{ env.VERSION }}"
          committer: "process-analytics-bot <62586190+process-analytics-bot@users.noreply.github.com>"
          author: "process-analytics-bot <62586190+process-analytics-bot@users.noreply.github.com>"
          branch: "infra/bump_bpmn_visualization_from_${{ env.OLD_VERSION }}_to_${{ env.VERSION }}"
          delete-branch: true
          base: "main"
          title: "[INFRA] Bump bpmn-visualization JS lib from ${{ env.OLD_VERSION }} to ${{ env.VERSION }}"
          body: "bpmn-visualization is updated from https://cdn.jsdelivr.net/npm/bpmn-visualization@${{ env.VERSION }}/dist/bpmn-visualization.min.js."
          labels: "dependencies"
          team-reviewers: pa-collaborators
          draft: true
